**Ex 1 - 1.	Implement univariate Linear regression using python. Read the data from a ‘.xlsx’ file and save the results to the file. Save the loss at every epoch and plot the graph for the same (Gradient descent). Experiment with polynomial regression with the same data towards nonlinear fit bold text.**

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
import math, copy

In [ ]:
house_model = pd.read_csv("/content/sample_data/california_housing_train.csv")
house_model.dropna(inplace = True)

In [ ]:
house_model.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
x = house_model.total_rooms
y = house_model.median_house_value

In [ ]:
x.head()

0    5612.0
1    7650.0
2     720.0
3    1501.0
4    1454.0
Name: total_rooms, dtype: float64

In [ ]:
y.head()

0    66900.0
1    80100.0
2    85700.0
3    73400.0
4    65500.0
Name: median_house_value, dtype: float64

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(x,y,train_size = 0.7 ,  random_state = 1)

In [ ]:
print(X_train.shape,X_test.shape)

(11900,) (5100,)

In [ ]:
x_train = X_train.to_numpy(dtype = 'double')
x_test = X_test.to_numpy(dtype = 'double')
y_train = y_train.to_numpy(dtype = 'double')
y_test = y_test.to_numpy(dtype = 'double')

In [ ]:
def compute_cost(x,y,w,b):
  m=x.shape[0]
  cost=0
  for i in range(m):
    f_wb = w*x[i] + b
    cost +=(f_wb - y[i])**2
  cost *= 1/(2*m)
  return cost

In [ ]:
def compute_gradient(x,y,w,b):
  m = x.shape[0]
  dj_dw = 0
  dj_db = 0

  for i in range(m):
    f_wb = w*x[i] + b
    dj_dw_i = (f_wb - y[i])* x[i]
    dj_db_i = (f_wb - y[i])

    dj_dw += dj_dw_i
    dj_db += dj_db_i
 
  dj_dw = dj_dw/m
  dj_db = dj_db/m

  return dj_dw, dj_db

In [ ]:
def gradient_descent(x,y,w_in,b_in,alpha,num_iters, cost_function, gradient_function):
  w = copy.deepcopy(w_in)
  j_history = []
  p_history = []
  b = b_in
  w = w_in

  for i in range(num_iters):
    dj_dw, dj_db = gradient_function(x,y,w,b)

    b = b-alpha*dj_db
    w = w-alpha*dj_dw


    # if i < 10000:
    #   j_history.append(cost_function(x,y,w,b))
    #   p_history.append([w,b])

    # if i%math.ceil(num_iters/10) == 0:
    #   print(f"Iteration {i:4}: Cost {j_history[-1]:0.2e} ",
    #               f"dj_dw: {dj_dw: 0.3e}, dj_db: {dj_db: 0.3e}  ",
    #               f"w: {w: 0.3e}, b:{b: 0.5e}")
      
  return w,b, j_history,p_history

In [ ]:
w_init = 0
b_init = 0

iterations = 1000
tmp_alpha = 1.0e-02

w_final,b_final,j_hist,p_hist = gradient_descent(x_train, y_train, w_init, b_init, tmp_alpha, iterations, compute_cost, compute_gradient)
print(f"(w,b) found by gradient descent: ({w_final},{b_final})")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in double_scalars

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in double_scalars
  if sys.path[0] == '':

(w,b) found by gradient descent: (nan,nan)